version: '3'
services:
  spacewalk:
    ports:
     - "5222:5222"
     - "443:443"
     - "80:80"
     - "69:69/udp"
     - "5269:5269"
    volumes:
      - "$PWD/data/centos7:/mnt"
      - "$PWD/data/spacewalk_status:/mnt2"
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres' 
    image: compus.physik.uni-greifswald.de:5000/marc/spacewalk
  postgres:
    links: ["spacewalk"]
    image: compus.physik.uni-greifswald.de:5000/marc/spacewalkpostgres
    volumes:
      - "$PWD/data/postgresql_data:/var/lib/postgresql/data"
    restart: always
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres' 

